### ISSUE TITLE
Binder not working, xarray not installed

### ISSUE THREAD

**Issue by rgommers** [intake/xrviz#77]
I just tried the Binder button in the readme; executing the first cell of the notebook ends in:
```
ModuleNotFoundError: No module named 'xarray'
```

**Comment by martindurant** [comment]
@hdsingh , do you have time to investigate? It seems to me that a simple environment file for binder would be better than a postbuild script.

**Comment by hdsingh** [comment]
I looked in for sometime and tried using this [environment.yml](https://github.com/hdsingh/xrviz/blob/master/binder/environment.yml). Although in the binder logs we have
```
Installing collected packages: xrviz
  Running setup.py develop for xrviz
Successfully installed xrviz
```
but still not able to import xarray. Not sure of the root cause.
[Complete Logs](https://gist.github.com/hdsingh/b3c82a2ef7b555ab993d3803879e46ea)

**Comment by martindurant** [comment]
Perhaps building this way means that the environment is not correctly activated on startup?

**Comment by hdsingh** [comment]
@rgommers Please feel free to explore more as binder example is working now. [Example Link](https://mybinder.org/v2/gh/intake/xrviz/master?filepath=examples%2Fgreat_lakes.ipynb). And thanks for bringing this to attention. :)

**Comment by rgommers** [comment]
Works like a charm now, thanks!
